version: 2.1

commands:
  setup_venv:
    steps:
      - restore_cache:
          name: Restore venv cache
          keys:
            - venv-{{ checksum ".python-version" }}-{{ checksum ".poetry-version" }}-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry config virtualenvs.create
            poetry config virtualenvs.in-project true
            poetry install
      - save_cache:
          name: Save venv cache
          key: venv-{{ checksum ".python-version" }}-{{ checksum ".poetry-version" }}-{{ checksum "poetry.lock" }}
          paths:
            - .venv

jobs:
  lint_and_test:
    docker:
      - image: cimg/python:3.10.4
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install poetry
          command: "pip install poetry==$(cat .poetry-version)"
      - setup_venv
      - run:
          name: Check formatting
          command: |
            source .venv/bin/activate
            black --check --diff spendthrift tests
      - run:
          name: Check import sort
          command: |
            source .venv/bin/activate
            isort --check --diff spendthrift tests
      - run:
          name: Check static typing
          command: |
            source .venv/bin/activate
            mypy spendthrift tests
      - run:
          name: Lint code
          command: |
            source .venv/bin/activate
            pylint spendthrift tests
      - run:
          name: Test code with coverage
          command: |
            source .venv/bin/activate
            pytest --cov=spendthrift tests

workflows:
  verify:
    jobs:
      - lint_and_test
